# cpmbining all the datasets in 1 csv with proper ratio

In [1]:
import pandas as pd

df_human = pd.read_csv("human_clean.csv")
df_mixtral = pd.read_csv("mixtral_clean.csv")
df_argugpt = pd.read_csv("arguGPT_clean.csv")

In [ ]:
df_human.head("full_text")

,Unnamed: 0,full_text,label,word_count
0,0,Phones\n\nModern humans today are always on th...,0,379
1,1,This essay will explain if drivers should or s...,0,366
2,2,Driving while the use of cellular devices\n\nT...,0,178
3,3,Phones & Driving\n\nDrivers should not be able...,0,212
4,4,Cell Phone Operation While Driving\n\nThe abil...,0,332

standardizing

In [5]:
df_ai = pd.concat([df_mixtral, df_argugpt], ignore_index=True)
df_ai = df_ai[["full_text", "label", "word_count"]]

In [6]:
df_ai.head()

                                           full_text  label  word_count
0  Storytelling Challenge: Crafting Compelling Na...      1         805
1  Storytelling Challenge: The Power of Narrative...      1         717
2  Storytelling Challenge: The Power of Narrative...      1         556
3  Storytelling Challenge: Crafting Compelling Na...      1         737
4  Storytelling Challenge: The Power of Narrative...      1         617

In [7]:
df_human = df_human[df_human["word_count"] > 200]
df_ai = df_ai[df_ai["word_count"] > 200]

In [8]:
n = min(len(df_human), len(df_ai))

df_human = df_human.sample(n, random_state=42)
df_ai = df_ai.sample(n, random_state=42)

In [9]:
df_final = pd.concat([df_human, df_ai], ignore_index=True)
df_final = df_final.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
df_final.columns

Index(['Unnamed: 0', 'full_text', 'label', 'word_count'], dtype='str')

In [11]:
df_final = df_final.drop(columns=["Unnamed: 0"])

In [12]:
df_final.columns

Index(['full_text', 'label', 'word_count'], dtype='str')

In [13]:
df_final.to_csv("final_raw_ds.csv", index=False)